version: "3.9"

services:
  surfshark-wireguard:
    build: .
    container_name: surfshark-wireguard
    environment:
      - SURFSHARK_USER=${SURFSHARK_USER}
      - SURFSHARK_PASSWORD=${SURFSHARK_PASSWORD}
      - NETWORK=192.168.100.0/24
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
      - 51413:51413
    restart: always
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    # network_mode: host # enable vpn on host machine

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=admin #optional
      - PASS=admin #optional
      - WHITELIST=*.*.*.* #optional
      # - HOST_WHITELIST=dnsnane list #optional
    volumes:
      - ./config:/config
      - /mnt/Server/Media:/downloads
    network_mode: service:surfshark-wireguard
    depends_on:
      - surfshark-wireguard
    restart: unless-stopped
