version: "3.9"

services:
  surfshark-wireguard:
    build: .
    container_name: surfshark-wireguard
    environment:
      - SURFSHARK_USER=${SURFSHARK_USER}
      - SURFSHARK_PASSWORD=${SURFSHARK_PASSWORD}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # sysctls:
    # - net.ipv4.conf.all.src_valid_mark=1
    # privileged: true
    # volumes:
    #   - /path/to/appdata/config:/config
    #   - /lib/modules:/lib/modules
    devices:
      - /dev/net/tun
    ports:
      - 8080:8080 #open port for qbittorrent
    restart: always
    dns:
      - 1.1.1.1
    # network_mode: host # enable vpn on host machine

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      #   - /path/to/appdata/config:/config
      - /mnt/Server/Media:/downloads
    depends_on:
      - surfshark-wireguard
    network_mode: service:surfshark-wireguard
    restart: always
